name: macos release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
        default: '1.0.0'


jobs:
  release:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - darwin/arm64
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Normalise version tag
        id: normalise_version
        shell: bash
        run: |
          if [ "${{ github.event.release.tag_name }}" == "" ]; then
            version=$(echo ${{ github.event.inputs.tag }} | sed -e 's/v//g')
            echo "version=$version" >> "$GITHUB_OUTPUT"
          else
            version=$(echo ${{ github.event.release.tag_name }} | sed -e 's/v//g')
            echo "version=$version" >> "$GITHUB_OUTPUT"
          fi
          
      - name: (Install) python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: (Install) python dev tools
        shell: bash
        run: python -m pip install pip wheel setuptools
      
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: (Install) dependencies
        shell: bash
        run: python -m pip install -r requirements.txt
      
      - name: (Install) pyinstaller
        shell: bash
        run: pip install pyinstaller
      
      - name: (Create) Executable
        shell: bash
        run: |
          pyinstaller rapidocr.spec

      - name: Upload release asset (DMG Package)
        uses: softprops/action-gh-release@v1
        with:
          tag: v${{ steps.normalise_version.outputs.version }}
          files: ./dist/rapidocr
          token: ${{ secrets.GITHUB_TOKEN }}