name: windows release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
        default: '0.0.1'


jobs:
  release:
    name: Release windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows/amd64
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: (Install) python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: (Install) python dev tools
        shell: bash
        run: python -m pip install pip wheel setuptools
      
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: (Install) dependencies
        shell: bash
        run: python -m pip install -r requirements.txt
      
      - name: (Install) pyinstaller
        shell: bash
        run: pip install pyinstaller
      
      - name: (Create) Executable
        shell: bash
        run: |
          pyinstaller rapidocr.spec
      
      - name: (Upload) binary
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.tag }}
          files: ./dist/rapidocr.exe
          token: ${{ secrets.GITHUB_TOKEN }}